name: Android CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    
    - uses: actions/checkout@v4
    
    - name: set up JDK 8
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: gradle

    - name: Build with Gradle
      run: "${{github.workspace}}/gradlew.bat"
